language: php
php:
  - '7.0'

# Commands to be run before your environment runs.
before_script:
  - composer self-update
  - composer global require "fxp/composer-asset-plugin:^1.2.1"
  - composer install -d src
  - mysql -e 'CREATE DATABASE vagrant_yii2_template_tests;'
script:
  - src/vendor/bin/codecept run unit -c src/codeception.yml 
